# Generated by Django 5.2.8 on 2025-11-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_request_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': (('moderator_access', 'Доступ модератора'),), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
