# Generated by Django 5.2.8 on 2025-11-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='patronymic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
