# Generated by Django 5.2.8 on 2025-11-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_advuser_patronymic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advuser',
            options={'permissions': (('moderator_access', 'Доступ модератора'),), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
