# Generated by Django 5.2.8 on 2025-11-13 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_advuser_options_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
