# Generated by Django 5.2.8 on 2025-11-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_request_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='worker_comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(upload_to='designs/', verbose_name='Дизайн'),
        ),
    ]
