# Generated by Django 5.2.8 on 2025-11-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_request_worker_comment_alter_request_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='worker_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
