# Generated by Django 5.2.8 on 2025-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_request_worker_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='completed/designs/', verbose_name='Выполненный дизайн'),
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(upload_to='designs/', verbose_name='Изначальный дизайн'),
        ),
        migrations.AlterField(
            model_name='request',
            name='worker_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комментарий дизайнеров'),
        ),
    ]
