# Generated by Django 5.2.8 on 2025-11-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_request_completed_image_alter_request_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='completed/', verbose_name='Выполненный дизайн'),
        ),
    ]
